### ISSUE TITLE
[keyword] 8장 - 의존성 관리하기

### ISSUE THREAD

**Issue by leejaeseung** [caffeine-library/objects#32]
## 주제

'8장 - 의존성 관리하기'을 읽고 내용을 요약하거나,  
중요✨ 하다고 생각하는 키워드 및 관련 설명을 코멘트로 달아주세요

## 연관 챕터

#31 

@caffeine-library/readers-objects

**Comment by leejaeseung** [comment]
## 의존성 해결
책에서 의존성 해결법을 아래와 같이 3가지 제시했습니다.
- 객체 생성 시점에 생성자를 통해 해결
- 객체 생성 후 setter 메서드를 통해 해결
- 메서드 실행 시 인자를 이용해 해결

책에선 setter 와 생성자를 혼합해서 사용하는게 시스템의 안정성 + 유연성을 향상시킬 수 있다고 하였는데, setter 를 통해 의존성을 해결하는 것 자체가 시스템의 안정성을 깨트리는 것이라고 생각되네요. 아무리 생성자를 통해 의존성을 주입받았다고 해도 이후에 그 의존성이 setter 로 인해 변경될 수 있기 때문에, 실행 중 특정 시점에 의존성에 대한 보장을 받을 수 없겠죠.

스프링에서도 생성자 주입, 수정자 주입 중 **생성자 주입**을 추천하는 걸 보면 수정자를 통한 의존성 주입은 위험한 방법이지 않나 싶습니다.

**Comment by wooyounggggg** [comment]
@leejaeseung 이전의 스프링 스터디에서 나왔던 [이슈](https://github.com/caffeine-library/pro-spring-5/issues/13)와 동일하여, 내용을 공유합니다.

**Comment by JasonYoo1995** [comment]
https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-dependencies

## Constructor-based or setter-based DI?

Since you can mix constructor-based and setter-based DI, it is a good rule of thumb to use constructors for mandatory dependencies and setter methods or configuration methods for optional dependencies. Note that use of the [@Required](https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans-required-annotation) annotation on a setter method can be used to make the property be a required dependency; however, constructor injection with programmatic validation of arguments is preferable.

The Spring team generally advocates constructor injection, as it lets you implement application components as immutable objects and ensures that required dependencies are not null. Furthermore, constructor-injected components are always returned to the client (calling) code in a fully initialized state. As a side note, a large number of constructor arguments is a bad code smell, implying that the class likely has too many responsibilities and should be refactored to better address proper separation of concerns.

Setter injection should primarily only be used for optional dependencies that can be assigned reasonable default values within the class. Otherwise, not-null checks must be performed everywhere the code uses the dependency. One benefit of setter injection is that setter methods make objects of that class amenable to reconfiguration or re-injection later. Management through [JMX MBeans](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#jmx) is therefore a compelling use case for setter injection.

Use the DI style that makes the most sense for a particular class. Sometimes, when dealing with third-party classes for which you do not have the source, the choice is made for you. For example, if a third-party class does not expose any setter methods, then constructor injection may be the only available form of DI.

**Comment by JasonYoo1995** [comment]
## 해석

생성자 주입과 세터 주입 중 어느 것을 해야 하는가?

필수적으로 의존해야 하는 객체는 생성자 주입을, 선택적으로 의존해야 하는 객체는 세터 주입을 권합니다.
물론, 세터 주입에 @Required 어노테이션을 붙여서 필수 의존성을 검증할 수 있지만
생성자 주입은 그 자체로 필수 의존 여부에 대한 검증이 가능하며, 그렇게 사용하길 권장됩니다.

스프링 팀은 일반적으로 생성자 주입을 옹호합니다.
Immutable한 객체로서 사용할 수 있고, 필수 의존 객체가 null이 아님을 보장하기 때문입니다.
게다가, 생성자 주입은 Client에게 완전히 초기화된 객체만을 반환해줍니다.
(참고로, 생성자에 인자가 너무 많으면 생성자를 사용하는 객체로 하여금 너무 많은 책임을 알게 하므로 이는 나쁜 코드 스멜인데
관심사를 분리함으로써 리팩토링 할 수 있습니다. → 우리 책 P.274의 '객체를 생성하는 곳과 객체를 사용하는 곳을 분리하라'는 내용과 비슷한 내용 같음)

세터 주입은 선택적인 의존성에 사용하되 종종 기본값과 함께 사용됩니다. 기본값을 사용하지 않으면, 사용하는 곳곳마다 null 체크를 해야 해서 좋지 않습니다. 세터 주입의 한 가지 장점은, 런타임 중 동적으로 재주입해야 하는 경우 유용하다는 것입니다. 이로 인해 JMX MBeans는 세터 주입을 강제합니다.

결론적으로, 상황에 따라 적절한 전략을 선택하면 됩니다. 때로는 소스 코드를 제공하지 않는 서드파티 클래스를 사용할 때는 기준이 달라질 수 있는데, 만약 서드파티 클래스가 세터 메서드를 제공하지 않는다면, 생성자 주입을 사용할 수 밖에 없을 것입니다.

**Comment by JasonYoo1995** [comment]
# 8. 의존성 관리하기
## 1) 의존성 이해하기
### 변경과 의존성
- 시점에 따른 의존성의 의미
  - 실행 시점 : 의존하는 객체가 존재해야 함 (NullPointException 방지)
  - 구현 시점 : 의존하는 클래스의 코드가 변경되면, 그것들 사용하는 클래스의 코드도 변경할 가능성이 생김
- 의존성의 종류
  - 메서드 파라미터로 받는 경우
  - 필드로 갖는 경우
  - 클래스를 상속하거나 인터페이스를 구현하는 경우
<img width=500 src=https://user-images.githubusercontent.com/66045861/167278932-966a14fb-4768-482c-927b-f535378b0bb2.png>

### 의존성 전이 (Transitive Dependency)
- 직접 의존성 / 간접 의존성
<img width=700 src=https://user-images.githubusercontent.com/66045861/167279021-ba652829-c14f-409c-905a-0c210abd3b9d.png>

- 출처 : 만들면서 배우는 클린 아키텍처 (자바 코드로 구현하는 클린 웹 어플리케이션) - P.14
<img width=600 src=https://user-images.githubusercontent.com/66045861/167279093-a8bf04ff-aeca-4d6f-b7e6-119762e6faaf.png>

### 런타임 의존성과 컴파일타임 의존성
### 컨텍스트 독립성
### 의존성 해결하기
## 2) 유연한 설계
### 의존성과 결합도
### 지식이 결합을 낳는다
### 추상화에 의존하라
### 명시적인 의존성
### new는 해롭다
### 가끔은 생성해도 무방하다
### 표준 클래스에 대한 의존은 해롭지 않다
### 컨텍스트 확장하기
### 조합 가능한 행동

**Comment by JasonYoo1995** [comment]
## 각주
1.
